Update postinst

diff --git a/neroaac/debian/postinst b/neroaac/debian/postinst
--- a/neroaac/debian/postinst
+++ b/neroaac/debian/postinst
@@ -15,7 +15,7 @@ case "$1" in
 
         mkdir -p $cache
         cd $cache
-        wget "ftp://ftp6.nero.com/tools/$archive" || ( echo "Couldn't download NeroAAC"; exit 1 )
+        wget "http://ftp6.nero.com/tools/$archive" || ( echo "Couldn't download NeroAAC"; exit 1 )
 
         sha256_2=$(sha256sum $archive | head -c64)
         if [ $sha256_2 != $sha256_1 ]; then
